#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  button,         sensorTouch)
#pragma config(Motor,  port2,           motor,         tmotorVex393_MC29, openLoop)
//*!!Code generated by 'ROBOTC' wizard Randy Kinne :-)               !!*//

/*
  Project Title: Transfer System
  Team Members: Randy Kinne, Trevor Rosario, Tylor Wallace
  Date: January 1st, 2016
  Section: 1.3.2


  Task Description:
  System that moves blocks between multiple points.
  Objective is to simulate an early assembly line.
  The process must be as efficient as possible.


  Pseudocode:
  System started manually between assemblies with a digital input.
  System will carry the assembly and make two stops, both of which are automated.
  Finished assembly will fall into a bin after the last automated stop.

  - System must come to a complete stop before each new part is completed
  - Includes an emergency stop button that stops all operations

  Overview:
  One manual start and two automated stops during assembly

  Optional:
  Reset button that resets the program back to the beginning of the assembly line.


*/



// TRANSFER SYSTEM



/** Description of startLine()
* Starts the assembly line
*/
void startLine()
{
	startMotor(port2, -35);
}



/** Description of stopLine()
* Stops the assembly line
*/
void stopLine()
{
	stopMotor(port2); // Stops the motor in port 2
}



/** Description of setEncoderValue(int value)
* @param value           Integer that sets the value on the encoder to 'VALUE'
* Sets the encoder to the value specified
*/
void setEncoderValue(int value)
{
	SensorValue[encoder] = value;
}



/** Description of checkEmergencyStop()
* Checks for a button press in case of manufacturing emergency to temporarily stop the line
*/
void checkEmergencyStop()
{
	if (SensorValue[button]==1) { // If button is being pressed
	stopLine(); // Stop line
	wait(1.5); // Waits 1.5 seconds to ensure the emergency is dealt with
	untilBump(button); // Restart button that restarts the line after it's been stopped via emergency stop
	startLine(); // Starts line
	}
}



/** Description of ENCODER_STOP
* Integer that controls the value at which the encoder stops.
*/
int ENCODER_STOP = 225;



/** Description of task main()
* Operates the assembly line
*/
task main()
{

setEncoderValue(0); // Sets the encoder value to 0 before we start anything

untilBump(button); // Wait until the start button is pressed then released to do anything

repeat(3) // Repeats 3 times
{

	setEncoderValue(0); // Sets the encoder value to 0 to ensure that the encoder values below remain relevant

	startLine(); // Start assembly line

	waitInMilliseconds(25); // Waits 25ms to prevent the emergency stop from being triggered by the initial start button on accident

	repeatUntil((SensorValue[encoder])>(ENCODER_STOP - 10)) { // Repeats until the encoder value reaches 25 less than var ENCODER_STOP (default: 225)
		checkEmergencyStop(); // Checks if the emergency button has been pressed and if so, handles it
		waitInMilliseconds(ENCODER_STOP/10); // Waits (default: 22.5 ms) between repeats to limit repeats until necessary
	}

	untilEncoderCounts(ENCODER_STOP, encoder); // Detects when the line has traveled to operator one

	stopLine(); // First automated stop at set distance

	wait(7); // Waits 7 seconds for the operator to finish and place the assembly back on the line
}

startTask(main); // Restarts this task to allow further assemblies to be built with the press of a button

}
